### ISSUE TITLE
Handle `old` value when generating patch CSV

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/app-manager#15]
When we [generate a patch CSV](https://github.com/everypolitician/github-event-handler/blob/b9ee6e1e031891653cd812f2d96a057dfe3c75c4/app/jobs/accept_submission_job.rb#L61-L69) we need to read the old value from everypolitician-data and add that to the generated CSV, currently we're just setting it to `nil`.

**Comment by tmtmtmtm** [comment]
It should really be the responsibility of the app that's generating the change to explain what value it's changing *from* as well as to. Otherwise there's a potential race-condition here that largely defeats the purpose of providing this information.

Imagine:

1. Official website transposes date and says that Joe Smith's birth_date is 1693
2. App downloads (and caches) this data
3. Simultaneously the official website gets corrected to accurate (and fuller) birth_date of 1963-12-13
4. Someone uses app to say that the 1693 is obviously incorrect, and it should be 1963

If the app submits that the patch is explicitly from "1693" to "1963" this will (correctly) fail to update if the original source has changed in the meantime.

However, if the app submits nothing, and we simply look up the current value at the point of submission, this will effectively say change _anything_ to 1963, and clobber the more correct change — which isn't what we want at all.

(If we _did_ ever want to do something like that, where we say "This information is so guaranteed correct that it overrides anything else from any source", then we should have a magic way of saying so explicitly)
