### ISSUE TITLE
External PR (EP#870) not triggering a viewer-sinatra PR

### ISSUE THREAD

**Issue by tmtmtmtm** [everypolitician/app-manager#34]
https://github.com/everypolitician/everypolitician-data/pull/870 hasn't triggered a parallel viewer-sinatra PR.

**Comment by chrismytton** [comment]
Ah interesting, so it looks like this is a slightly different error now:

```
Octokit::Conflict
POST https://api.github.com/repos/everypolitician/everypolitician-data/deployments: 409 - Conflict merging master into 92a1d071387d68bc2e38e62d1e129b420936d40c. // See: https://developer.github.com/v3
```

I think this is because the [`auto_merge` parameter when creating a deployment defaults to `true`](https://developer.github.com/v3/repos/deployments/#create-a-deployment), which means GitHub tries to merge master into the pull request, in this case unsuccessfully.

The simplest fix is to simply set `auto_merge` to `false`, which will just mean there will need to be some human intervention when the pull request gets merge to master, which happens anyway, so that seems reasonable.

**Comment by tmtmtmtm** [comment]
Yeah — I think we might need to look at doing something clever with making it easier to merge later (the way we do things at the minute means there's guaranteed to always be a conflict where two PRs are open simultaneously), but as we're having to resolve that by hand at the minute anyway, this sounds like a plausible option.
